<!--
    For .NET Standard packages, you can use the Nuget Package Manager in Visual Studio.
    For UWP / WinAppSDK / Uno packages, place the package references here.
-->
<Project>
  <!-- WinUI 2 / UWP -->
  <ItemGroup Condition="'$(IsUwp)' == 'true'">
  </ItemGroup>

  <!-- WinUI 3 / Uno -->
  <ItemGroup Condition="'$(IsUno)' == 'true' AND '$(WinUIMajorVersion)' == '3'">
  </ItemGroup>
</Project>
