<!--
    For .NET Standard packages, you can use the Nuget Package Manager in Visual Studio.
    For UWP / WinAppSDK / Uno packages, place the package references here.
-->
<Project>
  <!-- WinUI 2 / UWP -->
  <ItemGroup Condition="'$(IsUwp)' == 'true'">
    <PackageReference Include="Microsoft.Xaml.Behaviors.Uwp.Managed" Version="3.0.0"/>
  </ItemGroup>

  <!-- WinUI 3 / WinAppSdk -->
  <ItemGroup Condition="'$(IsWinAppSdk)' == 'true'">
    <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.0" />
  </ItemGroup>

  <!-- WinUI 3 / Uno -->
  <ItemGroup Condition="'$(IsUno)' == 'true' AND '$(WinUIMajorVersion)' == '3'">
    <PackageReference Include="Uno.Microsoft.Xaml.Behaviors.Interactivity.WinUI" Version="3.0.3" />
  </ItemGroup>
</Project>
